# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rejLZDUz32B4ifsAvvykp6V9UWJ2TFJ8
"""

from library import Library

def main_menu():

    my_lib = Library()

    print("Welcome to the Library Management System")

    while True:
        print("\nPlease choose an option:")
        print("1. Add a new book")
        print("2. Remove a book")
        print("3. Search for a book")
        print("4. Show all books")
        print("5. Exit")

        choice = input("Enter your choice (1-5): ")

        if choice == '1':
            title = input("Enter the book title: ")
            author = input("Enter the book author: ")
            my_lib.add_book(title, author)
        elif choice == '2':
            title = input("Enter the title of the book to remove: ")
            my_lib.remove_book(title)
        elif choice == '3':
            title = input("Enter the title of the book to search for: ")
            my_lib.search_book(title)
        elif choice == '4':
            my_lib.show_books()
        elif choice == '5':
            print("Goodbye!")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 5.")

if __name__ == "__main__":
    main_menu()