# -*- coding: utf-8 -*-
"""setup

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fldp7vhZpIPPFBl60QOtC_RcclvGs4yN
"""

from setuptools import setup, find_packages

setup(
    name='mylibrary',
    version='1.0.0',
    packages=find_packages(),
)