# -*- coding: utf-8 -*-
"""library.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XuRz9FG8jxCRaanPnLaGtNUdRlla-A7u
"""

class Library:

  def init(self):
    self.books = []

  def add_book(self, title, author):
    self.books.append({'title': title, 'author': author})

  def remove_book(self, title):
    book_to_remove = None
    for book in self.books:
        if book['title'].lower() == title.lower():
            book_to_remove = book
            break

    if book_to_remove:
        self.books.remove(book_to_remove)
        print(f"Book '{title}' removed successfully.")

  def search_book(self, title):
    for book in self.books:
      if book['title'].lower() == title.lower():
        print(f"I have the book. The title is {book['title']} and the auther is {book['author']}")
        return book
      else:
        print("i don't have this book")
    return None

  def show_books(self):
    if not self.books:
        print("The library is empty.")
    else:
        print("--- We have these books ---")
        for i, book in enumerate(self.books, 1):
            print(f"{i}. Title: {book['title']}, Author: {book['author']}")
        print("--------------------------")